In [24]:
import numpy as np
import matplotlib
matplotlib.use('Qt5Agg', warn=False, force=True)
import matplotlib.pyplot as plt
import itertools



def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """

    cm_orig = cm
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')
    
    plt.figure(figsize=(6, 6))
    matplotlib.rc('font', size=16)
    ttl = plt.title(title)
    ttl.set_position([.5, 1.05])
    plt.imshow(cm, interpolation='nearest', vmin=0, vmax=1, cmap=cmap)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)
    
    print(cm)

    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j , i + 0.07, cm_orig[i, j],
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    
    plt.subplots_adjust(left=0.14)

In [25]:
cm = np.array([[818, 133, 105,  65],
               [ 65, 210,   0,   6],
               [ 97,   1, 176,   8],
               [ 71,  10,   6, 196]])

target_names = ["0 Hz", "7.5 Hz", "10 Hz", "12 Hz"]
plot_confusion_matrix(cm, target_names, normalize=True, title="Convolutional Neural Network")
plt.show()

Normalized confusion matrix
[[ 0.72970562  0.11864407  0.09366637  0.05798394]
 [ 0.23131673  0.74733096  0.          0.02135231]
 [ 0.34397163  0.0035461   0.62411348  0.02836879]
 [ 0.25088339  0.03533569  0.02120141  0.69257951]]


In [26]:
cm = np.array([[778, 152, 127,  64],
               [ 26, 240,   4,  11],
               [ 63,   5, 202,  12],
               [ 40,  15,   6, 222]])

target_names = ["0 Hz", "7.5 Hz", "10 Hz", "12 Hz"]
plot_confusion_matrix(cm, target_names, normalize=True, title="Support Vector Machine with\nPloynomial (degree=3) Kernel")
plt.show()

Normalized confusion matrix
[[ 0.69402319  0.13559322  0.1132917   0.05709188]
 [ 0.09252669  0.85409253  0.01423488  0.03914591]
 [ 0.22340426  0.0177305   0.71631206  0.04255319]
 [ 0.14134276  0.05300353  0.02120141  0.7844523 ]]


In [27]:
cm = np.array([[465, 485,  88,  83],
               [ 86, 188,   5,   2],
               [ 96,  52, 124,  10],
               [104,  55,   1, 123]])

target_names = ["0 Hz", "7.5 Hz", "10 Hz", "12 Hz"]
plot_confusion_matrix(cm, target_names, normalize=True, title="Gaussian Naive Bayes Classifier")
plt.show()

Normalized confusion matrix
[[ 0.41480821  0.43264942  0.07850134  0.07404103]
 [ 0.30604982  0.66903915  0.01779359  0.00711744]
 [ 0.34042553  0.18439716  0.43971631  0.03546099]
 [ 0.36749117  0.19434629  0.00353357  0.43462898]]
